import type { Metadata } from "next";
import "./globals.css";
import NavBar from "./NavBar";
import { ibmPlexSans, poppins } from "./fonts";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${ibmPlexSans.variable} ${poppins.variable} antialiased`}>
        <NavBar />
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
